version: '3.8'
services:
  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  post-db:
    image: postgres
    container_name: post-db
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: user_db
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  user-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
